from tkinter import *
root=Tk()
root.title("tk2")
root.iconbitmap("C:/Users/har22/.vscode/Google Chat.ico")
root.geometry("700x140")
txtbox1 = Label(root, text = "Grid GUI" )
myl2=Label(root, text = "line 2")
txtbox1.grid(row=0,column=1)
myl2.grid(row=1,column=2)
root.mainloop()